#!/usr/bin/env python3
"""Generate a constrained Terraform VPC configuration and open a pull request."""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "generated" / "vpc"
MODEL_ID = os.environ.get("BEDROCK_MODEL_ID", "anthropic.claude-3-haiku-20240307-v1:0")


def validate_cidr(value: str) -> str:
    """Return a canonical network CIDR, rejecting host bits and non-IPv4 input."""
    try:
        network = ipaddress.ip_network(value, strict=True)
    except ValueError as error:
        raise ValueError("cidr must be an IPv4 network address, for example 10.42.0.0/16") from error
    if network.version != 4 or not 16 <= network.prefixlen <= 28:
        raise ValueError("cidr prefix must be between /16 and /28")
    return str(network)


def validate_model_config(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError("Bedrock response must be a JSON object")
    name = value.get("name")
    region = value.get("region", "us-east-1")
    dns_support = value.get("enable_dns_support", True)
    dns_hostnames = value.get("enable_dns_hostnames", True)
    if not isinstance(name, str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9-]{0,62}", name):
        raise ValueError("Bedrock returned an invalid VPC name")
    if not isinstance(region, str) or not region or len(region) > 30:
        raise ValueError("Bedrock returned an invalid AWS region")
    if not isinstance(dns_support, bool) or not isinstance(dns_hostnames, bool):
        raise ValueError("Bedrock DNS settings must be boolean")
    return {
        "name": name,
        "region": region,
        "enable_dns_support": dns_support,
        "enable_dns_hostnames": dns_hostnames,
    }


def ask_bedrock(cidr: str, request: str) -> dict[str, Any]:
    import boto3

    prompt = (
        "Return ONLY JSON with keys name, region, enable_dns_support, "
        "enable_dns_hostnames. Do not include markdown or Terraform. "
        f"The required IPv4 CIDR is {cidr}. User request: {request or 'a sensible default VPC'}"
    )
    client = boto3.client("bedrock-runtime", region_name=os.environ.get("AWS_REGION", "us-east-1"))
    response = client.converse(
        modelId=MODEL_ID,
        messages=[{"role": "user", "content": [{"text": prompt}]}],
        inferenceConfig={"temperature": 0, "maxTokens": 300},
    )
    text = response["output"]["message"]["content"][0]["text"]
    try:
        return validate_model_config(json.loads(text))
    except (KeyError, json.JSONDecodeError, ValueError) as error:
        raise ValueError(f"Bedrock returned invalid configuration: {error}") from error


def render(cidr: str, config: dict[str, Any]) -> None:
    """Render only the fixed module invocation; model output never becomes Terraform."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "main.tf").write_text(
        f'''module "vpc" {{
  source = "../../modules/vpc"

  name                 = {json.dumps(config["name"])}
  cidr                 = {json.dumps(cidr)}
  enable_dns_support   = {str(config["enable_dns_support"]).lower()}
  enable_dns_hostnames = {str(config["enable_dns_hostnames"]).lower()}
}}
''',
        encoding="utf-8",
    )
    (OUTPUT_DIR / "provider.tf").write_text(
        f'''variable "aws_region" {{
  description = "AWS region for the generated VPC."
  type        = string
  default     = {json.dumps(config["region"])}
}}

provider "aws" {{
  region = var.aws_region
}}
''',
        encoding="utf-8",
    )


def run(*command: str) -> None:
    subprocess.run(command, cwd=ROOT, check=True)


def create_pr(cidr: str) -> None:
    branch = f"generated-vpc-{cidr.replace('/', '-')}"
    run("git", "checkout", "-B", branch)
    run("git", "add", "generated/vpc/main.tf", "generated/vpc/provider.tf")
    run("git", "commit", "-m", f"Generate VPC configuration for {cidr}")
    run("git", "push", "--set-upstream", "origin", branch)
    run(
        "gh",
        "pr",
        "create",
        "--title",
        f"Generate VPC configuration for {cidr}",
        "--body",
        "Generated by AWS Bedrock. Terraform apply is intentionally not performed; review and approve this PR before deployment.",
        "--base",
        os.environ.get("GITHUB_BASE_REF", "main"),
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cidr", required=True)
    parser.add_argument("--request", default="")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    try:
        cidr = validate_cidr(args.cidr)
        config = ask_bedrock(cidr, args.request)
        render(cidr, config)
        if not args.dry_run:
            create_pr(cidr)
    except (ValueError, RuntimeError, subprocess.CalledProcessError) as error:
        print(f"generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
